[package]
name = "mlb-api-proc"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
itertools = "0.14.0"
syn = { version = "2.0.106", features = ["full"] }
quote = "1.0.40"
proc-macro2 = "1.0.101"
derive-syn-parse = "0.2.0"
